<?php

namespace RestFull\RestFullBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function getNumberOfUser() {

        $qb = $this->createQueryBuilder('c');
        $qb->select('COUNT(c)');
        die($qb->getQuery()->getSingleResult());
        return $qb->getQuery()->getSingleResult();
    }

    public function a() {
        die('coucou');
    }

    public function insertUser() {

        die('insertion d\'un user');
    }
}
