rest_full_rest_full:
    resource: "@RestFullRestFullBundle/Controller/"
    type:     annotation
    prefix:   /

#root:
#    pattern: /
#    defaults:
#        _controller: AppFrontBundle:Default:index
#        path: /
#        permanent: true
