User:
    type: entity
    table: user
    uniqueConstraints:
        mail:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        lastname:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        firstname:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 40
            fixed: false
            comment: ''
        role:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
